services:
    eliza:
        platform: linux/amd64
        command: ["pnpm", "start", "--character=./characters/eliza.character.json"]
        image: eliza-starter:v1
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - DISCORD_APPLICATION_ID=
            - DISCORD_API_TOKEN=
            - REDPILL_API_KEY=
            - SERVER_PORT=3000
        ports:
            - "3000:3000"
        restart: always
